In [2]:
import numpy as np

In [3]:
data_list = [1,2,3,4]
array = np.array(data_list)
print(array)

[1 2 3 4]


In [4]:
data_list = [[1,2,3],[4,5,6],[7,8,9]]
array = np.array(data_list)
print(array)
print(array.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [5]:
# like range()
# start,stop,step
np.arange(0,10)
np.arange(0,10,2)


array([0, 2, 4, 6, 8])

In [6]:
np.zeros(3)
np.zeros((3,4))
np.ones(4)

array([1., 1., 1., 1.])

In [7]:
# Return evenly spaced numbers over a specified interval
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [8]:
#  identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
# This function generates random numbers from a uniform distribution between 0 and 1.

np.random.rand(5)
np.random.rand(5,5)

# This function generates random numbers from a standard normal distribution (mean 0, variance 1).
np.random.randn(6)

np.random.randint(1,10,5)

array([9, 7, 4, 2, 4])

In [10]:
data_list = [[1,2,3],[4,5,6],[7,8,9]]
array = np.array(data_list)
print(array)

array.reshape(1,9)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [11]:
array.max()
array.min()

# location of max value
array.argmax()
# location of min value
array.argmin()
# shape
array.shape
# type
array.dtype

dtype('int64')

In [12]:
array = np.arange(0,11)
# indexing
print(array[0])
# slicing
print(array[0:3])
# replace values with 100
array[0:3] = 100
print(array)
# replace values with 0
array[:] = 0
print(array)

0
[0 1 2]
[100 100 100   3   4   5   6   7   8   9  10]
[0 0 0 0 0 0 0 0 0 0 0]


In [13]:
# copy
array_copy = array.copy()
print(array_copy)

[0 0 0 0 0 0 0 0 0 0 0]


In [14]:
array = np.arange(0,9)
array = array.reshape(3,3)
print(array[1,2])
print(array[1][2])
print(array[:2,1:])

5
5
[[1 2]
 [4 5]]


In [15]:
# array of true / false
bool_array = array > 5 
print(bool_array)
# conditional selection
print(array[bool_array])


[[False False False]
 [False False False]
 [ True  True  True]]
[6 7 8]


In [16]:
array[:] = array[:] * 10
print(array)

[[ 0 10 20]
 [30 40 50]
 [60 70 80]]


In [25]:
# Operations
array_1 = np.arange(0,4)
array_2 = np.arange(5,9)
# add elements by elements
print(array_1 + array_2)
# substracts elements by elements
print(array_1 - array_2)
# multiply elements by elements
print(array_1 * array_2)
# add 100 to all elements
print(array_1 + 100)
# square of all elements
print(array_1 ** 2)
# square root
print(np.sqrt(array_1))
# exponential
print(np.exp(array_1))
# max
print(array_1.max())
# min
print(array_1.min())
# exponential
print(np.sin(array_1))
# log
print(np.log(array_1))


[ 5  7  9 11]
[-5 -5 -5 -5]
[ 0  6 14 24]
[100 101 102 103]
[0 1 4 9]
[0.         1.         1.41421356 1.73205081]
[ 1.          2.71828183  7.3890561  20.08553692]
3
0
[0.         0.84147098 0.90929743 0.14112001]
[      -inf 0.         0.69314718 1.09861229]


<ipython-input-25-8c1c69af0766>:25: RuntimeWarning: divide by zero encountered in log
  print(np.log(array_1))
